wxDatabase: wxDatabaseErrorReporter Class Reference
wxDatabaseErrorReporter Class Reference
#include <error_reporter.h>
Detailed Description
Definition at line 6 of file error_reporter.h.
Public Member Functions
wxDatabaseErrorReporter ()
virtual ~wxDatabaseErrorReporter ()
const wxString & GetErrorMessage ()
int GetErrorCode ()
void ResetErrorCodes ()
Protected Member Functions
void SetErrorMessage (const wxString &strErrorMessage)
void SetErrorCode (int nErrorCode)
void ThrowDatabaseException ()
Private Attributes
wxString m_strErrorMessage
int m_nErrorCode
Constructor & Destructor Documentation
wxDatabaseErrorReporter()
wxDatabaseErrorReporter::wxDatabaseErrorReporter ()
Definition at line 3 of file error_reporter.cpp.
References ResetErrorCodes().
~wxDatabaseErrorReporter()
wxDatabaseErrorReporter::~wxDatabaseErrorReporter () virtual
Definition at line 8 of file error_reporter.cpp.
Member Function Documentation
GetErrorCode()
int wxDatabaseErrorReporter::GetErrorCode ()
Definition at line 17 of file error_reporter.cpp.
References m_nErrorCode.
Referenced by ThrowDatabaseException().
GetErrorMessage()
const wxString & wxDatabaseErrorReporter::GetErrorMessage ()
Definition at line 12 of file error_reporter.cpp.
References m_strErrorMessage.
Referenced by ThrowDatabaseException().
ResetErrorCodes()
void wxDatabaseErrorReporter::ResetErrorCodes ()
Definition at line 32 of file error_reporter.cpp.
References m_nErrorCode, m_strErrorMessage, and wxDATABASE_OK.
Referenced by wxDatabaseErrorReporter().
SetErrorCode()
void wxDatabaseErrorReporter::SetErrorCode (int nErrorCode) protected
Definition at line 27 of file error_reporter.cpp.
References m_nErrorCode.
Referenced by wxDatabase::GetSingleResultBlob(), wxDatabase::GetSingleResultBool(), wxDatabase::GetSingleResultDate(), wxDatabase::GetSingleResultDouble(), wxDatabase::GetSingleResultInt(), wxDatabase::GetSingleResultLong(), and wxDatabase::GetSingleResultString().
SetErrorMessage()
void wxDatabaseErrorReporter::SetErrorMessage (const wxString & strErrorMessage) protected
Definition at line 22 of file error_reporter.cpp.
References m_strErrorMessage.
Referenced by wxDatabase::GetSingleResultBlob(), wxDatabase::GetSingleResultBool(), wxDatabase::GetSingleResultDate(), wxDatabase::GetSingleResultDouble(), wxDatabase::GetSingleResultInt(), wxDatabase::GetSingleResultLong(), and wxDatabase::GetSingleResultString().
ThrowDatabaseException()
void wxDatabaseErrorReporter::ThrowDatabaseException () protected
Definition at line 38 of file error_reporter.cpp.
References GetErrorCode(), and GetErrorMessage().
Referenced by wxDatabase::GetSingleResultBlob(), wxDatabase::GetSingleResultBool(), wxDatabase::GetSingleResultDate(), wxDatabase::GetSingleResultDouble(), wxDatabase::GetSingleResultInt(), wxDatabase::GetSingleResultLong(), and wxDatabase::GetSingleResultString().
Member Data Documentation
m_nErrorCode
int wxDatabaseErrorReporter::m_nErrorCode private
Definition at line 28 of file error_reporter.h.
Referenced by GetErrorCode(), ResetErrorCodes(), and SetErrorCode().
m_strErrorMessage
wxString wxDatabaseErrorReporter::m_strErrorMessage private
Definition at line 27 of file error_reporter.h.
Referenced by GetErrorMessage(), ResetErrorCodes(), and SetErrorMessage().