wxDatabase: wxDatabaseStringConverter Class Reference
wxDatabaseStringConverter Class Reference
#include <string_converter.h>
Detailed Description
Definition at line 6 of file string_converter.h.
Public Member Functions
wxDatabaseStringConverter ()
wxDatabaseStringConverter (const wxChar *charset)
virtual ~wxDatabaseStringConverter ()
void SetEncoding (wxFontEncoding encoding)
void SetEncoding (const wxCSConv *conv)
const wxCSConv * GetEncoding ()
virtual const wxCharBuffer ConvertToUnicodeStream (const wxString &inputString)
virtual size_t GetEncodedStreamLength (const wxString &inputString)
virtual wxString ConvertFromUnicodeStream (const char *inputBuffer)
virtual wxString ConvertFromUnicodeStream (const wxChar *inputBuffer)
Static Public Member Functions
static const wxCharBuffer ConvertToUnicodeStream (const wxString &inputString, const char *encoding)
static wxString ConvertFromUnicodeStream (const char *inputBuffer, const char *encoding)
static size_t GetEncodedStreamLength (const wxString &inputString, const char *encoding)
static wxString ConvertFromUnicodeStream (const wxChar *inputBuffer, const char *encoding)
Private Attributes
wxCSConv m_Encoding
Constructor & Destructor Documentation
wxDatabaseStringConverter() [1/2]
wxDatabaseStringConverter::wxDatabaseStringConverter ()
Definition at line 4 of file string_converter.cpp.
wxDatabaseStringConverter() [2/2]
wxDatabaseStringConverter::wxDatabaseStringConverter (const wxChar * charset)
Definition at line 9 of file string_converter.cpp.
~wxDatabaseStringConverter()
virtual wxDatabaseStringConverter::~wxDatabaseStringConverter () inline virtual
Definition at line 14 of file string_converter.h.
Member Function Documentation
ConvertFromUnicodeStream() [1/4]
wxString wxDatabaseStringConverter::ConvertFromUnicodeStream (const char * inputBuffer) virtual
Definition at line 61 of file string_converter.cpp.
ConvertFromUnicodeStream() [2/4]
wxString wxDatabaseStringConverter::ConvertFromUnicodeStream (const wxChar * inputBuffer) virtual
Definition at line 71 of file string_converter.cpp.
ConvertFromUnicodeStream() [3/4]
static wxString wxDatabaseStringConverter::ConvertFromUnicodeStream (const char * inputBuffer, const char * encoding) static
ConvertFromUnicodeStream() [4/4]
static wxString wxDatabaseStringConverter::ConvertFromUnicodeStream (const wxChar * inputBuffer, const char * encoding) static
ConvertToUnicodeStream() [1/2]
const wxCharBuffer wxDatabaseStringConverter::ConvertToUnicodeStream (const wxString & inputString) virtual
Definition at line 24 of file string_converter.cpp.
Referenced by GetEncodedStreamLength().
ConvertToUnicodeStream() [2/2]
static const wxCharBuffer wxDatabaseStringConverter::ConvertToUnicodeStream (const wxString & inputString, const char * encoding) static
GetEncodedStreamLength() [1/2]
size_t wxDatabaseStringConverter::GetEncodedStreamLength (const wxString & inputString) virtual
Definition at line 42 of file string_converter.cpp.
References ConvertToUnicodeStream().
GetEncodedStreamLength() [2/2]
size_t wxDatabaseStringConverter::GetEncodedStreamLength (const wxString & inputString, const char * encoding) static
Definition at line 98 of file string_converter.cpp.
References ConvertToUnicodeStream().
GetEncoding()
const wxCSConv* wxDatabaseStringConverter::GetEncoding () inline
Definition at line 18 of file string_converter.h.
SetEncoding() [1/2]
void wxDatabaseStringConverter::SetEncoding (wxFontEncoding encoding)
Definition at line 14 of file string_converter.cpp.
References m_Encoding.
SetEncoding() [2/2]
void wxDatabaseStringConverter::SetEncoding (const wxCSConv * conv)
Definition at line 19 of file string_converter.cpp.
References m_Encoding.
Member Data Documentation
m_Encoding
wxCSConv wxDatabaseStringConverter::m_Encoding private
Definition at line 31 of file string_converter.h.
Referenced by SetEncoding().